apiVersion: batch/v1
kind: Job
metadata:
  name: rails-prepare-job-{{ .Release.Revision }}
  namespace: match
  annotations:
    {{- with .Values.dbPrepareJob.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.useArgoSyncWaveAnnotations }}
    {{- toYaml .Values.dbPrepareJob.argoSyncWaveAnnotations | nindent 4 }}
    {{- else }}
    {{- toYaml .Values.dbPrepareJob.helmHookAnnotations | nindent 4 }}
    {{- end }}
spec:
  template:
    spec:
      serviceAccountName: {{ include "match.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Never
      containers:
        - name: rails-db-prepare
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          args: ["bin/rails", "db:prepare"]
          env:
           {{- include "match.envVars" . | nindent 12 }}
           {{- include "match.owningUserEnvVars" . | nindent 12 }}
          volumeMounts:
           {{- include "match.volumeMounts" . | nindent 12 }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      volumes:
        {{- include "match.volumes" . | nindent 8 }}
