{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "match.serviceAccountName" . }}
  labels:
    {{- include "match.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.useArgoSyncWaveAnnotations }}
    {{- toYaml .Values.serviceAccount.argoSyncWaveAnnotations | nindent 4 }}
    {{- else }}
    {{- toYaml .Values.serviceAccount.helmHookAnnotations | nindent 4 }}
    {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
